FROM XFROM_CONTAINERX

COPY *.deb /debs/

#XXX Would be better to make the list of packages an ARG or file in the
#    dockerdir so that this whole repo could all be generic...

RUN    apt-get update \
    && apt-get install -y --no-install-recommends \
           kmod \
           net-tools \
           isc-dhcp-client \
           inetutils-ping \
           dnsutils \
           wpasupplicant \
           openntpd \
           nvi \
           ca-certificates \
           procps \
           busybox-syslogd \
           /debs/*.deb \
    && rm -rf /debs \
    && rm -rf /var/lib/apt/lists/*

COPY init /
COPY fstab /etc/
COPY wpa_supplicant.conf /usr/local/etc
COPY mkwpaconf /usr/local/sbin
COPY startdocker /usr/local/sbin
COPY netd /usr/local/sbin
COPY sethostname /etc/dhcp/dhclient-exit-hooks.d
