#!/bin/sh

# Wait a little for devices to appear.
sleep 2

# Mount the necessary filesystems.
# We need /proc to mount anything, /dev to mount /boot,
# and /boot for the new root image.
mount /proc
mount /dev
mount /boot

# Switch to the real root.

LAYERS=
FILTERS="-f/dev/null"
mount_layers() {
    name=$1
    dir=/boot/layers
    for i in `fgrep -v $FILTERS $dir/$name.layers`; do
        mount -tsquashfs $dir/$i.sqfs $dir/$i
        LAYERS=$dir/$i:$LAYERS
    done
    FILTERS="$FILTERS -f$dir/$name.layers"
}

mount_layers rootfs
# XXX debugging: add more layers
#mount_layers python3
#mount_layers storagemgr
mount -toverlay overlay -olowerdir=${LAYERS%:} /newroot

# XXX debugging: mount a writable overlay on top of /
#mount -ttmpfs tmpfs -osize=128M /boot/overlay
#mkdir /boot/overlay/root
#mkdir /boot/overlay/work
#mount -toverlay overlay \
#      -olowerdir=/newroot \
#      -oupperdir=/boot/overlay/root \
#      -oworkdir=/boot/overlay/work \
#      /newroot

# Move existing mounts to the new root.
mount --move /proc /newroot/proc
mount --move /dev /newroot/dev
mount --move /boot /newroot/boot
# XXX debugging: leave old root visible under the new root
#mount --bind / /newroot/mnt

exec switch_root /newroot /sbin/init
