#!/bin/sh

# Wait a little for devices to appear.
sleep 2

# Mount the necessary filesystems.
# We need /proc to mount anything, /dev to mount /boot,
# and /boot for the new root image.
mount /proc
mount /dev
#Try all partitions until one has /layers/rootfs.layers
for i in `egrep -o ' (mmcblk[0-9]+p[0-9]+|[sh]d[a-z]+[0-9]+)$' /proc/partitions`; do
    #XXX Maybe check that it is fat/vfat/exfat before trying to mount?
    #XXX Mount read-only
    if ! mount /dev/$i /boot; then
        continue
    fi
    if [ -f /boot/layers/rootfs.layers ]; then
        break
    fi
    umount /boot
done
if ! [ -f /boot/layers/rootfs.layers ]; then
    echo "FAILED TO MOUNT /boot" >&2
    # drop into shell
    setsid -c /bin/sh -l
    exit 99
fi

# Switch to the real root.

LAYSERSDIR=/boot/layers
mount -tsquashfs $LAYSERSDIR/fs.sqfs $LAYSERSDIR/fs

LAYERS=
FILTERS="-f/dev/null"
add_layers() {
    name=$1
    for i in `fgrep -v $FILTERS $LAYSERSDIR/$name.layers`; do
        LAYERS=$LAYSERSDIR/fs/$i:$LAYERS
    done
    FILTERS="$FILTERS -f$LAYSERSDIR/$name.layers"
}

add_layers rootfs
# XXX debugging: add more layers
#add_layers python3
#add_layers storagemgr
#add_layers dnsd
mount -toverlay overlay -olowerdir=${LAYERS%:} /newroot

# XXX debugging: mount a writable overlay on top of /
#mount -ttmpfs tmpfs -osize=128M /boot/overlay
#mkdir /boot/overlay/root
#mkdir /boot/overlay/work
#mount -toverlay overlay \
#      -olowerdir=/newroot \
#      -oupperdir=/boot/overlay/root \
#      -oworkdir=/boot/overlay/work \
#      /newroot

# Move existing mounts to the new root.
mount --move /proc /newroot/proc
mount --move /dev /newroot/dev
mount --move /boot /newroot/boot
# XXX debugging: leave old root visible under the new root
#mount --bind / /newroot/mnt

echo "initrd finished, switching roots"
exec switch_root /newroot /sbin/init
