#!/bin/sh

mount -a

hostname `cat /etc/hostname`

syslogd -C64
klogd -c5

echo 5 >/proc/sys/kernel/panic

modprobe brcmfmac
(netd &)

startdocker

#XXX eventually this will be some form of getty
setsid -cw bash -l

netd -k
umount -a
sync
