#!/bin/sh

# Set PATH.
# This does two things:
#     1. Set the path for ourselves.
#     2. Give subprocesses a path.
#        While dash provides a default path if we are started
#        without one, it it not exported.  So do that here.

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

mount -a

hostname `cat /etc/hostname`

syslogd -C64
klogd -c5

echo 5 >/proc/sys/kernel/panic

modprobe brcmfmac
(netd &)

mkdir -p /tmp/docker/etc
mount -t tmpfs tmpfs /var/lib/docker
mount --bind /tmp/docker/etc /etc/docker
startdocker

#XXX eventually this will be some form of getty
setsid -cw bash -l

netd -k
umount -a
sync
