#!/bin/sh

mount -a

hostname `cat /etc/hostname`

syslogd -C64
klogd -c5

echo 5 >/proc/sys/kernel/panic

modprobe brcmfmac
(netd &)

mkdir -p /tmp/docker/etc
mount -t tmpfs tmpfs /var/lib/docker
mount --bind /tmp/docker/etc /etc/docker
startdocker

#XXX eventually this will be some form of getty
setsid -cw bash -l

netd -k
umount -a
sync
