#!/bin/sh

# The default mode is to run interactively in the foreground.
# We use -t for that because it buffers stdout otherwise.
# Then we also have to use -i to make control-C work.
# Otherwise, it kills the docker process but leaves the container
# running detached.
# If we don't give -i or -t, then it runs in the foreground
# but is not interruptable.  We use this mode for instances
# started by storaged.
dockerargs="-it"
cmd=storagemgr
mounts="--mount=type=bind,src=/dev,dst=/dev
        --mount=type=bind,src=/mnt,dst=/mnt,bind-propagation=shared"

if [ "$1" = -d ]; then
    # noninteraction, storagemgr in daemon mode
    dockerargs=""
    cmd="$cmd -d"
    shift
elif [ "$1" = -s ]; then
    # interactive shell for debugging
    cmd=bash
    shift
    if [ -f /.bashrc ]; then
        mounts="$mounts --mount=type=bind,src=/.bashrc,dst=/root/.bashrc"
    fi
fi

exec docker run --rm --privileged \
    $mounts \
    -e ACTION="$ACTION" \
    -e SUBSYSTEM="$SUBSYSTEM" \
    -e MDEV="$MDEV" \
    $dockerargs storagemgr $cmd "$@"
