#!/bin/sh

# The default mode is to run in foreground.  We use -t for that
# because it buffers stdout otherwise.  Then we also have to use
# -i to make control-C work.  Otherwise, it kills the docker
# process but leaves the container running detached.
dockerargs="-it"
cmd=storagemgr

if [ "$1" = -d ]; then
    # background, detached docker, storagemgr in daemon mode
    dockerargs="-d"
    cmd="$cmd -d"
    shift
elif [ "$1" = -s ]; then
    # interactive shell
    cmd=bash
    shift
fi

exec docker run --rm --privileged \
    --mount=type=bind,src=/.bashrc,dst=/root/.bashrc \
    --mount=type=bind,src=/dev,dst=/dev \
    --mount=type=bind,src=/mnt,dst=/mnt,bind-propagation=shared \
    -e ACTION="$ACTION" \
    -e SUBSYSTEM="$SUBSYSTEM" \
    -e MDEV="$MDEV" \
    $dockerargs storagemgr $cmd "$@"
