#!/bin/sh

# The default mode is to run interactively in the foreground.
# We use -t for that because it buffers stdout otherwise.
# Then we also have to use -i to make control-C work.
# Otherwise, it kills the docker process but leaves the container
# running detached.
# Daemon mode (-d) runs docker with -d (detached) and dnsd with -d
# (log to syslog).
createargs="-it"
startargs="-i"
name=dnsd
cmd=dnsd
mounts="--mount=type=bind,src=/dev/log,dst=/dev/log"

if [ "$1" = -d ]; then
    # noninteraction, dnsd in daemon mode
    createargs=""
    startargs=""
    cmd="$cmd -d"
    shift
elif [ "$1" = -s ]; then
    # interactive shell for debugging
    cmd=bash
    name=dnsd-sh
    shift
    if [ -f /.bashrc ]; then
        mounts="$mounts --mount=type=bind,src=/.bashrc,dst=/root/.bashrc"
    fi
fi

docker container create \
    --rm --name="$name" $createargs $mounts \
    --network=bridge --publish=53:53/tcp --publish=53:53/udp \
    --cap-add=NET_BIND_SERVICE \
    dnsd $cmd "$@"
docker network connect --ip=172.18.0.2 private "$name"
exec docker container start $startargs "$name"
