#!/bin/sh

if ! grep -q '^cgroup /sys/fs/cgroup tmpfs' < /proc/mounts; then
    mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
    (
        cd /sys/fs/cgroup
        for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
            mkdir -p $sys
            if ! mountpoint -q $sys; then
                if ! mount -n -t cgroup -o $sys cgroup $sys; then
                    rmdir $sys || true
                fi
            fi
        done
    )
fi

dockerd -p /var/run/dockerd.pid 2>&1 | logger -p daemon.info -t dockerd &

while ! docker info >/dev/null 2>&1; do
    sleep 0.5
done

if ! docker images | grep -q ^debian; then
    for i in /boot/layers/*.layers; do
        if [ "$i" = "/boot/layers/rootfs.layers" ]; then continue; fi

        for layer in `cat $i`; do
            if mountpoint -q /boot/layers/$layer; then continue; fi
            mount -tsquashfs /boot/layers/$layer.sqfs /boot/layers/$layer
        done

        unsplit-tar ${i%.*} /boot/layers | docker load

        for layer in `cat $i`; do
            if [ "$i" = "/boot/layers/rootfs.layers" ]; then continue; fi
            DIRNAME=`grep $layer /var/lib/docker/image/overlay2/layerdb/sha256/*/diff | cut -d'/' -f9`
            CACHEID=`cat /var/lib/docker/image/overlay2/layerdb/sha256/$DIRNAME/cache-id`
            if [ -h /var/lib/docker/overlay2/$CACHEID ]; then continue; fi

            rm -rf /var/lib/docker/overlay2/$CACHEID/diff
            ln -sf /boot/layers/$layer /var/lib/docker/overlay2/$CACHEID/diff
        done
    done
fi
