#!/bin/sh

progname="${0##*/}"

usage() {
    {
    echo "Usage: $progname [-s] env-file command..."
    echo "    -s   save env-file after execution"
    } >&2
   exit 99
}

while getopts s opt; do
    case $opt in
    (s)
	sflag=1
	;;
    (\?)
	usage
	;;
    esac
done
shift $(($OPTIND - 1))
if [ $# -lt 2 ]; then
   usage
fi
envfile="$1"
shift

if [ ! -f $envfile ]; then
    touch $envfile
fi

flockargs=-s
fakerootargs="-i$envfile"
if [ "$sflag" ]; then
    flockargs=-x
    fakerootargs="$fakerootargs -s$envfile"
fi

exec flock $flockargs $envfile fakeroot $fakerootargs "$@"
