#!/bin/bash

#XXX Allow appending more --include packages.

#XXX Make these options!
MIRROR="http://ftp.debian.org/debian/"

usage () {
    echo "Usage: $0 [-a ARCH] RELEASE ROOTDIR" >&2
    exit 99
}

if [ $UID -ne 0 ]; then
    echo "$0 must be run as root!" >&2
    exit 99
fi

while getopts ":a:" opt; do
    case $opt in
        a)
            ARCH=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
	    ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ -z "$ARCH" ]; then
    ARCH=`uname -m`
fi

if [ -z "$1" ]; then
    echo "Missing release name." >&2
    usage
fi
REL="$1"

if [ ! -d "$2" ]; then
    echo "$2 doesn't exist or isn't a directory." >&2
    usage
fi
DIR="$2"

if ! debootstrap --foreign --variant=minbase --include=debian-archive-keyring --arch=$ARCH "$REL" "$DIR" "$MIRROR"; then
    echo debootstrap failed! >&2
    exit 10
fi

cut -c5- <<EOF >$DIR/debootstrap/finish
    #!/bin/sh

    mount -t proc proc /proc &&
    mount -t sysfs sys /sys &&
    /debootstrap/debootstrap --second-stage &&
    rm -f $DIR/var/cache/apt/archives/partial/*.deb &&
    rm -f $DIR/var/cache/apt/archives/*.deb &&
    echo "root:badpass" | chpasswd &&
    touch /etc/.image_finished

    sync #We panic the guest kernel to exit, so make sure cache is flushed.
EOF
chmod a+x $DIR/debootstrap/finish

mkdir -p $DIR/etc/network
cut -c5- <<EOF >$DIR/etc/network/interfaces
    auto eth0
    iface eth0 inet dhcp
EOF

echo "$REL" > $DIR/etc/hostname

cut -c5- <<EOF >$DIR/etc/apt/sources.list
    deb http://httpredir.debian.org/debian $REL main contrib non-free
    deb http://httpredir.debian.org/debian $REL-updates main contrib non-free
    deb http://security.debian.org $REL/updates main contrib non-free
EOF

#XXX --include locales,dbus in debootstrap.

#XXX? /etc/fstab?  May not be needed w/ systemd.
#XXX? enable getty (and root login) on ttyS0?  Seems to just work.

#XXX? Strip man pages?  /usr/share/doc?  /usr/share/locale?  or just localepurge?
