#!/bin/bash

#XXX Make these options!
MIRROR="http://ftp.debian.org/debian/"

#XXX Allow appending more --include packages on cmdline.
#XXX Passing the keyring to --include doesn't seem to work during 2nd-stage.
#    Copy keyring into rootfs?  This may break when debian-archive-keyring is
#    installed during the 2nd-stage.  Perhaps pass the host keyring to debootstrap here?
#    Symptom is debootstrap rewriting apt srcs from http to https due to missing keyring.
INCLUDES=debian-archive-keyring

usage () {
    echo "Usage: $0 [-a ARCH] RELEASE ROOTDIR [extra_deb_URLs]*" >&2
    exit 99
}

if [ $UID -ne 0 ]; then
    echo "$0 must be run as root!" >&2
    exit 99
fi

while getopts ":a:" opt; do
    case $opt in
        a)
            ARCH=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
	    ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ -z "$ARCH" ]; then
    ARCH=`uname -m`
fi

if [ -z "$1" ]; then
    echo "Missing release name." >&2
    usage
fi
REL="$1"
shift

if [ ! -d "$1" ]; then
    echo "$1 doesn't exist or isn't a directory." >&2
    usage
fi
DIR="$1"
shift

#Download the extra debs, the in-guest script will install them.
mkdir -p $DIR/extra_debs
for url in "$@"; do
    if ! wget -qP $DIR/extra_debs/ $url; then
        echo "wget $url failed" >&2
        exit 9
    fi
done
#Add all the .deb's deps to --include=.  debootstrap will do recursive deps.
for deb in $DIR/extra_debs/*.deb; do
    INCLUDES+=",`dpkg -I $deb | grep '^ Depends: ' | cut -d' ' -f3- | sed 's/([^)]*)//g' | tr -d ' '`"
done

if ! debootstrap --foreign --variant=minbase --include=$INCLUDES --arch=$ARCH "$REL" "$DIR" "$MIRROR"; then
    echo debootstrap failed! >&2
    exit 10
fi

cut -c5- <<EOF >$DIR/debootstrap/finish
    #!/bin/sh

    mount -t proc proc /proc &&
    mount -t sysfs sys /sys &&
    export PATH=/usr/bin:/bin:/sbin:/usr/sbin &&
    /debootstrap/debootstrap --second-stage &&
    dpkg -i /extra_debs/*.deb &&
    rm -rf /extra_debs &&
    rm -f /var/cache/apt/archives/partial/*.deb &&
    rm -f /var/cache/apt/archives/*.deb &&
    echo "root:badpass" | chpasswd &&
    touch /etc/.image_finished

    echo
    echo
    echo "Don't worry, this panic is normal:"
    sync #We panic the guest kernel to exit, so make sure cache is flushed.
EOF
chmod a+x $DIR/debootstrap/finish

mkdir -p $DIR/etc/network
cut -c5- <<EOF >$DIR/etc/network/interfaces
    auto eth0
    iface eth0 inet dhcp
EOF

echo "$REL" > $DIR/etc/hostname

cut -c5- <<EOF >$DIR/etc/apt/sources.list
    deb http://httpredir.debian.org/debian $REL main contrib non-free
    deb http://httpredir.debian.org/debian $REL-updates main contrib non-free
    deb http://security.debian.org $REL/updates main contrib non-free
EOF

#XXX --include locales,dbus in debootstrap.

#XXX? /etc/fstab?  May not be needed w/ systemd.
#XXX? enable getty (and root login) on ttyS0?  Seems to just work.

#XXX? Strip man pages?  /usr/share/doc?  /usr/share/locale?  or just localepurge?
