#!/bin/bash

if [ -z "$1" -o -z "$2" ]; then
    echo "Usage: $0 ARCH PREFIXDIR"
    exit 99
fi

ARCH="$1"
PREFIXDIR="$2"

sed "s/XARCHX/$ARCH/g" | rev | cut -d'/' -f1 | rev | \
    egrep -v '^[[:blank:]]*#|^[[:blank:]]*$' | sed "s_^_$PREFIXDIR/_"
