#!/bin/bash

# wget wrapper that checks CACHEDIR first.

while getopts ":O:" opt; do
    case $opt in
        O)
            file="$OPTARG"
            ;;
        :)
            echo "WGET WRAPPER: getopts parse failure" >&2
            exit 99
            ;;
    esac
done

if [ -n "$WGETWRAPPER" ]; then
    echo "WGET WRAPPER: Called recursively, PATH problem" >&2
    exit 99
fi

if [ ! -d "$CACHEDIR" ]; then
    echo "WGET WRAPPER: CACHEDIR not set or doesn't exist" >&2
    exit 99
fi

#Peel the wget wrapper off the front of $PATH
PATH=`echo $PATH | cut -d':' -f2-`

echo wget "$@" >> /tmp/wgets
echo "FILE: $file" >> /tmp/wgets

cache_file="$CACHEDIR/`basename $file`"
if [ -f "$cache_file" ]; then
    cp "$cache_file" "$file"
else
    export WGETWRAPPER=1
    if wget "$@"; then
        cp "$file" "$cache_file"
    else
        exit $?
    fi
fi

exit 0
