#!/usr/bin/python3

import argparse
import dnslib as dl
import dnslib.server as ds
import socketserver as ss
import json
import requests
import socket
import threading
import syslog
import traceback

opts = None
log = None
zone = {}

def main():
    parse_args()

    global log
    log = Log("dnsd", opts)

    run()

    return 0

def parse_args(args = None):
    a = argparse.ArgumentParser()
    a.add_argument("-f", "--file",
                   action = "store", default = None,
                   help = "data file name")
    a.add_argument("-a", "--addr",
                   action = "store", default = "0",
                   help = "dns listen address")
    a.add_argument("-p", "--port", type = int,
                   action = "store", default = 53,
                   help = "dns listen port number")
    a.add_argument("-A", "--ctrladdr",
                   action = "store", default = "dnsd-control",
                   help = "control socket address")
    a.add_argument("-P", "--ctrlport", type = int,
                   action = "store", default = 54,
                   help = "control socket port number")
    a.add_argument("-d", "--daemon",
                   action = "store_true",
                   help = "daemon mode, log to syslog")
    a.add_argument("-v", "--verbose",
                   action = "count", default = 0,
                   help = "verbose, log more")

    global opts
    opts = a.parse_args(args)

def run():
    global zone
    zone = Zone(opts.addr, opts.port)

    if opts.file is not None:
        with open(opts.file) as f:
            jzone = json.load(f)
        log.verbose2(json.dumps(jzone, indent = 4))
        origin, extaddr, ttl, jdata = jzone
        zone.init(origin, extaddr, ttl, jdata)

    zone.start()

    ctrl = CtrlServer((opts.ctrladdr, opts.ctrlport))
    ctrl.start()

class Zone(object):
    logger = ds.DNSLogger("request,-request") # don't log

    def __init__(self, addr, port):
        self.addr = addr
        self.port = port
        self.origin = None
        self.ttl = None
        self.extaddr = None
        self.db = {}
        self.lock = threading.Lock()
        self.resolver = None
        self.udp = None
        self.tcp = None

    def init(self, origin, extaddr, ttl, jdata = None):
        if jdata is None:
            jdata = {
                "@": [
                    ["SOA", "ns", "hostmaster",
                            [1, 3600, 300, 3600000, 3600000]],
                    ["NS", "ns"],
                    ["A", "@"]
                ],
                "ns": [
                    ["A", "@"]
                ]
            }
        with self.lock:
            try:
                assert self.origin is None
                self.origin = Zone.mklabel(origin)
                self.extaddr = extaddr
                self.ttl = ttl
                assert self.db == {}
                for name, jrds in jdata.items():
                    name = self.fqdn(name)
                    rds = []
                    for jrd in jrds:
                        rd = self.mkrd(jrd[0], jrd[1:])
                        if rd is None:
                            raise RuntimeError("unknown RR type %s" %
                                               (jrd[0]))
                        rds.append(rd)
                    self.db[name] = rds
            except Exception:
                # undo partial initialization
                self.origin = None
                self.extaddr = None
                self.tel = None
                self.db = {}
                raise

    def initialized(self):
        return self.origin is not None

    def start(self):
        log.info("listening on %s port %s" % (self.addr, self.port))
        self.resolver = Resolver(self)
        self.udp = ds.DNSServer(self.resolver,
                                address = self.addr, port = self.port,
                                tcp = False, logger = self.logger)
        self.udp.start_thread()
        self.tcp = ds.DNSServer(self.resolver,
                                address = self.addr, port = self.port,
                                tcp = True, logger = self.logger)
        self.tcp.start_thread()

    def get(self, label, default):
        return self.db.get(label, default)

    def add(self, name, type, value):
        assert self.origin is not None
        name = self.fqdn(name)
        log.verbose("add: %s %s %s" % (name, type, value))
        nrd = self.mkrd(type, value)
        if nrd is None:
            return False

        with self.lock:
            rds = self.get(name, [])
            log.verbose("add: old rds %s" % (rds))
            rds.append(nrd)
            self.db[name] = rds
            log.verbose("add: new rds %s" % (rds))

        return True

    def delete(self, name, type):
        assert self.origin is not None
        name = self.fqdn(name)
        log.verbose("delete: %s %s" % (name, type))
        type = self.mktype(type)
        if type is None:
            return False

        with self.lock:
            if type == dl.QTYPE.ANY:
                del self.db[name]
                return True
            ords = self.get(name, [])
            log.verbose("delete: old rds %s" % (ords))
            nrds = []
            for ord in ords:
                if ord[0] != type:
                    nrds.append(ord)
            self.db[name] = nrds
            log.verbose("delete: new rds %s" % (nrds))

        return True

    def mkrd(self, jtype, jvalue):
        jtype = jtype.lower()
        if type(jvalue) is not list:
            jvalue = (jvalue,)
        if jtype == "soa":
            return (dl.QTYPE.SOA,
                    dl.SOA(self.fqdn(jvalue[0]),
                           self.fqdn(jvalue[1]),
                           jvalue[2]))
        if jtype == "ns":
            return (dl.QTYPE.NS, dl.NS(self.fqdn(jvalue[0])))
        if jtype == "a":
            return (dl.QTYPE.A, dl.A(self.modaddr(jvalue[0])))
        if jtype == "cname":
            return (dl.QTYPE.CNAME, dl.CNAME(self.fqdn(jvalue[0])))
        if jtype == "mx":
            return (dl.QTYPE.MX, dl.MX(self.fqdn(jvalue[0]), jvalue[1]))
        if jtype == "txt":
            return (dl.QTYPE.TXT, dl.TXT(jvalue[0]))
        if jtype == "ptr":
            return (dl.QTYPE.PTR, dl.PTR(self.fqdn(jvalue[0])))
        return None

    def mktype(self, jtype):
        jtype = jtype.lower()
        if jtype == "any":
            return dl.QTYPE.ANY
        if jtype == "ns":
            return dl.QTYPE.NS
        if jtype == "a":
            return dl.QTYPE.A
        if jtype == "cname":
            return dl.QTYPE.CNAME
        if jtype == "mx":
            return dl.QTYPE.MX
        if jtype == "txt":
            return dl.QTYPE.TXT
        if jtype == "ptr":
            return dl.QTYPE.PTR
        return None

    def fqdn(self, name):
        """
        Turn name (a string) into a fully qualified domain name,
        and return it as a DNSLabel.
        """
        if name == "@":
            return self.origin
        if name[-1] == ".":
            return Zone.mklabel(name)
        return self.origin.add(name.lower())

    def mklabel(name):
        return dl.DNSLabel(name.lower())

    def modaddr(self, addr):
        if addr == "@":
            return self.extaddr
        return addr

class Resolver(ds.BaseResolver):
    def __init__(self, zone):
        self.zone = zone

    def resolve(self, request, handler):
        try:
            log.verbose("request:\n%s" % (request))
            reply = self.resolve1(request)
        except Exception as e:
            log.error("%s" % traceback.format_exc())
            reply = request.reply(ra = 0, aa = 1)
            reply.header.rcode = dl.RCODE.SERVFAIL
        log.verbose("reply:\n%s" % (reply))
        return reply

    def resolve1(self, request):
        reply = request.reply(ra = 0, aa = 1)
        if request.q.qtype == dl.QTYPE.AXFR:
            reply.header.rcode = dl.RCODE.REFUSED
            return reply
        with self.zone.lock:
            # this works even before zone is initialized
            additional = set()
            if request.q.qclass == dl.CLASS.IN:
                self.add_answer(reply, additional, request.q.qname)
            self.add_authority(reply, additional)
            # additional processing
            for name in additional:
                self.add_additional(reply, name, dl.QTYPE.A)
        return reply

    def add_answer(self, reply, additional, name, level = 0):
        #
        # The basic idea is to return all records that match the query.
        # Some complications are ANY queries, following CNAME, and
        # keeping track of names to put in the additional section.
        # Not all features are supported, like subdomain referral,
        # because we don't got none of those.
        #
        if level > 10:
            raise RuntimeError("CNAME loop in resolving %s" %
                               (str(reply.q.qname)))
        # To avoid NXDOMAIN caching before we're populated, no result
        # is not considered an error.
        # This is also correct when following CNAME.
        rds = self.zone.get(Zone.mklabel(str(name)), [])
        qtype = reply.q.qtype
        for r in rds:
            if (qtype != dl.QTYPE.ANY and
                qtype != r[0] and
                r[0] != dl.QTYPE.CNAME):
                continue
            rr = dl.RR(rname = name,
                       rtype = r[0],
                       rclass = reply.q.qclass,
                       ttl = self.zone.ttl,
                       rdata = r[1])
            reply.add_answer(rr)
            if (r[0] == dl.QTYPE.CNAME and
                qtype != dl.QTYPE.CNAME and
                qtype != dl.QTYPE.ANY):
                self.add_answer(reply, additional, r[1].label, level + 1)
            elif r[0] == dl.QTYPE.NS or r[0] == dl.QTYPE.MX:
                additional |= {r[1].label}

    def add_authority(self, reply, additional):
        name = self.zone.origin
        for r in self.zone.get(name, []):
            if r[0] == dl.QTYPE.NS:
                rr = dl.RR(rname = name,
                           rtype = r[0],
                           rclass = reply.q.qclass,
                           ttl = self.zone.ttl,
                           rdata = r[1])
                reply.add_auth(rr)
                additional |= {r[1].label}

    def add_additional(self, reply, name, type):
        for r in self.zone.get(name, []):
            if r[0] == type:
                rr = dl.RR(rname = name,
                           rtype = r[0],
                           rclass = reply.q.qclass,
                           ttl = self.zone.ttl,
                           rdata = r[1])
                reply.add_ar(rr)

class CtrlServer(ss.TCPServer):
    allow_reuse_address = True
    def __init__(self, addr):
        super().__init__(addr, CtrlRequest, True)

    def start(self):
        log.info("listening on %s port %s ctrl" %
                 (self.server_address[0], self.server_address[1]))
        self.serve_forever()

class CtrlRequest(ss.StreamRequestHandler):
    dirty = False
    def handle(self):
        try:
            request = self.rfile.readline().strip().decode("us-ascii")
            request = json.loads(request)
            log.verbose("ctrl: %s" % (json.dumps(request)))
            reply = self.handle1(request)
        except (TypeError, ValueError) as e:
            log.warning("%s" % traceback.format_exc())
            reply = (1, "Invalid request: %s" % (str(e)))
        except Exception as e:
            log.error("%s" % traceback.format_exc())
            reply = (10, str(e))
        try:
            reply = (json.dumps(reply) + "\n").encode("us-ascii")
            self.wfile.write(reply)
        except Exception as e:
            log.error("%s" % traceback.format_exc())

    def handle1(self, request):
        cmd, *args = request
        if cmd == "init":
            if zone.initialized():
                return (1, "Zone already initialized")
            origin, extaddr, ttl = args
            return self.init(origin, extaddr, ttl)
        if not zone.initialized():
            return (1, "Zone not initialized")
        if cmd == "add":
            name, type, value = args
            return self.add(name, type, value)
        if cmd == "delete":
            name, type = args
            return self.delete(name, type)
        return (1, "Unknown request")

    def init(self, origin, extaddr, ttl):
        zone.init(origin, extaddr, ttl)
        return (0, "Success")

    def add(self, name, type, value):
        if not zone.add(name, type, value):
            return (1, "Invalid resource type or value")
        return (0, "Success")

    def delete(self, name, type):
        if not zone.delete(name, type):
            return (1, "Invalid resource type")
        return (0, "Success")

class Log(object):
    def __init__(self, name, opts):
        self.daemon = opts.daemon
        self.level = opts.verbose
        if self.daemon:
            syslog.openlog(name, 0, syslog.LOG_DAEMON)
    def _log(self, priority, msg):
        for line in msg.split("\n"):
            if line == "":
                continue
            if self.daemon:
                syslog.syslog(priority, line)
            else:
                print(line)
    def info(self, msg):
        self._log(syslog.LOG_INFO, msg)
    def warning(self, msg):
        self._log(syslog.LOG_WARNING, msg)
    def error(self, msg):
        self._log(syslog.LOG_ERR, msg)
    def verbose(self, msg):
        if self.level > 0:
            self._log(syslog.LOG_INFO, msg)
    def verbose2(self, msg):
        if self.level > 1:
            self._log(syslog.LOG_INFO, msg)

if __name__ == "__main__":
    try:
        exit(main())
    except KeyboardInterrupt:
        pass
    except Exception:
        if log:
            log.error("%s" % traceback.format_exc())
        else:
            traceback.print_exc()
    exit(1)
